In [3]:
import pandas as pd

path = '/Users/mitchjohnson/Documents/NPPES/NPPES_Data_Dissemination_January_2024/npidata_pfile_20050523-20240107.csv'
cols = ['Entity Type Code', 'NPI', 'Provider Organization Name (Legal Business Name)', 'Provider Enumeration Date', 'Last Update Date', 'NPI Deactivation Date', 'NPI Reactivation Date', 'Healthcare Provider Taxonomy Code_1', 'Healthcare Provider Taxonomy Code_2']
df_nppes = pd.read_csv(path, usecols=cols)
df_nppes.rename(columns={'Entity Type Code':'code', 'Provider Organization Name (Legal Business Name)':'OrgName'}, inplace=True)
df_nppes

/var/folders/gn/lqpzq41d6pzbxzs9wj58d8_c0000gn/T/ipykernel_24491/568840270.py:5: DtypeWarning: Columns (39,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df_nppes = pd.read_csv(path, usecols=cols)

,NPI,code,OrgName,Provider Enumeration Date,Last Update Date,NPI Deactivation Date,NPI Reactivation Date,Healthcare Provider Taxonomy Code_1,Healthcare Provider Taxonomy Code_2
0,1679576722,1.0,NaN,05/23/2005,07/08/2007,NaN,NaN,207X00000X,NaN
1,1588667638,1.0,NaN,05/23/2005,05/29/2014,NaN,NaN,207RC0000X,207RC0000X
2,1497758544,2.0,"CUMBERLAND COUNTY HOSPITAL SYSTEM, INC",05/23/2005,09/26/2011,NaN,NaN,251G00000X,NaN
3,1306849450,NaN,NaN,NaN,NaN,03/03/2021,NaN,NaN,NaN
4,1215930367,1.0,NaN,05/23/2005,11/25/2014,NaN,NaN,174400000X,207RH0003X
...,...,...,...,...,...,...,...,...,...
8131403,1083484505,1.0,NaN,01/05/2024,01/05/2024,NaN,NaN,1041C0700X,NaN
8131404,1700656220,1.0,NaN,01/05/2024,01/05/2024,NaN,NaN,174400000X,NaN
8131405,1528838042,1.0,NaN,01/05/2024,01/05/2024,NaN,NaN,171100000X,NaN
8131406,1346010865,1.0,NaN,01/05/2024,01/05/2024,NaN,NaN,106E00000X,NaN
8131407,1164292686,1.0,NaN,01/05/2024,01/05/2024,NaN,NaN,363LP0808X,NaN

In [4]:
df_nppes.shape
#df[df.ein != '<UNAVAIL>']

(8131408, 9)

In [11]:
path2 = '/Users/mitchjohnson/Documents/NPPES/inputs/Practice NPIs from Richard.csv'
df_richard = pd.read_csv(path2)
df_richard

              NPI
0      1124038963
1      1811168263
2      1831276823
3      1962501940
4      1467762021
...           ...
11376  1992975775
11377  1992981583
11378  1992981971
11379  1992984918
11380  1992987200

[11381 rows x 1 columns]

In [16]:
df_richard_nppes = pd.merge(df_nppes, df_richard, on='NPI', how='inner')
df_richard_nppes.shape

(11379, 9)

In [17]:
df_richard_nppes.groupby('code').size()

code
1.0       86
2.0    11281
dtype: int64

In [22]:
richard_pathname = '/Users/mitchjohnson/Documents/NPPES/outputs/richard_type_1s.csv'
df_richard_nppes[df_richard_nppes.code == 1.0].NPI.to_csv(richard_pathname, index=False)

In [23]:
path3 = '/Users/mitchjohnson/Documents/NPPES/inputs/Hema Group NPIs.csv'
df_hema = pd.read_csv(path3)
df_hema

            NPI
0    1003016775
1    1003017823
2    1003207978
3    1033138607
4    1033469390
..          ...
182  1972532042
183  1972616738
184  1982613113
185  1982741971
186  1982830956

[187 rows x 1 columns]

In [25]:
df_hema_nppes = pd.merge(df_nppes, df_hema, on='NPI', how='inner')
df_hema_nppes.groupby('code').size()

code
1.0     35
2.0    149
dtype: int64

In [26]:
hema_pathname = '/Users/mitchjohnson/Documents/NPPES/outputs/hema_type_1s.csv'
df_hema_nppes[df_hema_nppes.code == 1.0].NPI.to_csv(hema_pathname, index=False)